# Configuration Settings for the Rover Rx

# GNSS/INS Parameters

device: tcp://192.168.3.1:28784

serial:
  baudrate: 921600
  rx_serial_port: USB1
  hw_flow_control: off

login:
  user: ""
  password: ""

frame_id: ins

imu_frame_id: imu

poi_frame_id: base_link

vsm_frame_id: vsm

aux1_frame_id: aux1

vehicle_frame_id: base_link

get_spatial_config_from_tf: false

lock_utm_zone: true

use_ros_axis_orientation: true

receiver_type: ins

multi_antenna: false

datum: WGS84
# WGS84:    Equivalent to Default
# ETRS89:   European ETRS89 (ETRF2000 realization)
# NAD83:    NAD83(2011), North American Datum (2011)
# NAD83_PA: NAD83(PA11), North American Datum, Paciﬁc plate (2011)
# NAD83_MA: NAD83(MA11), North American Datum, Marianas plate (2011)
# GDA94:    GDA94(2010), Geocentric Datum of Australia (2010)
# GDA2020:  GDA2020, Geocentric Datum of Australia 2020

poi_to_arp:
  delta_e: 0.0
  delta_n: 0.0
  delta_u: 0.0

att_offset:
  heading: 90.0
  pitch: 0.0
  
ant_type: "AERAT1675_382 NONE"
ant_serial_nr: ""
ant_aux1_type: "AERAT1675_382 NONE"
ant_aux1_serial_nr: ""

# ant_type:
# - PolaNt Choke Ring B3/E6: "SEPCHOKE_B3E6 SPKE", "SEPCHOKE_B3E6 NONE" 
# - Veraphase 6000: "TWIVP6050_CONE NONE"
# - PolaNt-x-MF: "SEPPOLANT_X_MF NONE"
# - PolaNt*MC: "AERAT1675_382 NONE"

leap_seconds: 18

polling_period:
  pvt: 1000
  rest: 20

use_gnss_time: false

ntrip_settings:
  mode: off
  caster: 0
  caster_port: 0
  username: 0
  password: 0
  mountpoint: 0
  ntrip_version: v2
  send_gga: auto
  rx_has_internet: false
  rtcm_version: RTCMv3
  rx_input_corrections_tcp: 62001
  rx_input_corrections_serial: USB2

publish:
  # For both GNSS and INS Rxs
  navsatfix: true
  gpsfix: false
  gpgga: false
  gprmc: false
  gpst : false
  measepoch: false
  pvtcartesian: false
  pvtgeodetic: false
  poscovcartesian: false
  poscovgeodetic: true
  velcovgeodetic: false
  atteuler: false
  attcoveuler: true
  pose: true
  pose_with_covariance: true
  diagnostics: true
  # For GNSS Rx only
  gpgsa: false
  gpgsv: false
  # For INS Rx only
  insnavcart: false
  insnavgeod: true
  extsensormeas: false
  imusetup: false
  velsensorsetup: false
  exteventinsnavcart: false
  exteventinsnavgeod: false
  imu: false
  localization: false
  tf: false

# INS-Specific Parameters

ins_spatial_config:
  imu_orientation:
    theta_x: 180.0
    theta_y: 0.0
    theta_z: 0.0
  poi_lever_arm:
    delta_x: 0.0
    delta_y: 0.0
    delta_z: 0.0
  ant_lever_arm:
    x: 0.195
    y: -0.340
    z: -0.024
  vel_sensor_lever_arm:
    vsm_x: 0.0
    vsm_y: 0.0
    vsm_z: 0.0

ins_initial_heading: auto

ins_std_dev_mask:
  att_std_dev: 5.0
  pos_std_dev: 10.0

ins_use_poi: false

# Logger

activate_debug_log: true

diagnostics: # enable: publish.diagnostics == true
  hardware_id: septentrio_Asterx_SBi3
  check_rate: 1.0 # sec

# Additional Settings (INS Only)

navsatfix_output:
  navsatfix_topic: /sensing/ins/asterx_i3/navsatfix

coordinate_convert:
  coordinate: MGRS
  height_type: Orthometric
  plane_num: 7
  correct_meridian_convergence: true

  # coordinate:
  # - PLANE
  # - MGRS

  # height_type:
  # - Orthometric (標高)
  # - Ellipsoid (楕円体高)

  # plane_num (Required PLANE output only): 1 ~ 19
  
  # correct_meridian_convergence: 子午線収差角補正

pose_output:
  pose_topic: /sensing/ins/asterx_i3/pose
  pose_with_cov_topic: /sensing/ins/asterx_i3/pose_with_covariance

baselink_pose_output:
  config_from_tf: false
  
  # using config_from_tf == false
  ins_to_baselink:
    x: 0.65
    y: 0.0
    z: 1.353

  pose_topic: /sensing/ins/base_link/pose
  pose_with_cov_topic: /sensing/ins/base_link/pose_with_covariance

output_stopping_limit:
  max_longitude_covariance: 10.0
  max_latitude_covariance: 10.0
  max_height_covariance: 50.0

  INSNavGeod_Error_enable: [7, 20, 21, 23, 24, 28, 29, 30, 31, 32]

  # 7:  position output prohibited due to export laws
  # 20: INS solution not requested by user
  # 21: not enough valid external sensor measurements
  # 23: static alignment ongoing
  # 24: waiting for GNSS PVT
  # 28: in-motion alignment ongoing
  # 29: waiting for GNSS heading
  # 30: waiting for the IMU to synchronize with PPS from the receiver
  # 31: standard deviation of the INS solution exceeds user limit set by the setINSStdDevMask command
  # 32: unsupported settings in INS

  # 7:  輸出法によりポジション出力禁止
  # 20: ユーザーが要求していないINSソリューション
  # 21: 十分な有効な外部センサー測定値がありません
  # 23: 静的アライメント進行中
  # 24: GNSS PVT を待機中
  # 28: インモーションアライメント進行中
  # 29: GNSSヘディングを待っています
  # 30: IMUが受信機からのPPSと同期するのを待っています
  # 31: INSソリューションの標準偏差が、setINSStdDevMask コマンドによって設定されたユーザー制限を超えています
  # 32: INSでサポートされていない設定
